<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <RollForward>Major</RollForward>
    <PublishReadyToRun>false</PublishReadyToRun>
    <TieredCompilation>false</TieredCompilation>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="MonoGame.Framework.DesktopGL" Version="3.8.2.1105" />
    <PackageReference Include="MonoGame.Content.Builder.Task" Version="3.8.2.1105" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\KekLib2D.Core\KekLib2D.Core.csproj" />
    <ProjectReference Include="..\..\KekLib3D\KekLib3D.csproj" />
    <ProjectReference Include="..\..\KekLib3D.Voxels\KekLib3D.Voxels.csproj" />
  </ItemGroup>
</Project>
